### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by eam12** [achtman-lab/GrapeTree#107]
Thank you so much for creating GrapeTree! I've been successfully using the GrapeTree command line module for generating trees for several years with no problem...until now.

For some reason, the newest profiles I am generating are leading to a `MemoryError`. I have confirmed that the module still works with older profiles and with the [example simulated_data.profile](https://github.com/achtman-lab/GrapeTree/blob/master/examples/simulated_data.profile) available on this page. I have compared the old, new, and example profile files and the formats look identical. I'm really not sure what the issue is. Can anyone enlighten me? 

I've included the complete error message below and have attached a toy profile that is giving me this error.

```
% grapetree --profile cgMLST0_toy.txt --method MSTreeV2 --n_proc $SLURM_NTASKS > cgMLST0_toy.nwk

Traceback (most recent call last):
  File "/home/johnsont/shared/.conda/envs/grapetree_2.1/lib/python3.6/site-packages/grapetree/module/MSTrees.py", line 291, in _asymmetric
    shortcuts = get_shortcut(wdist, weight)
  File "/home/johnsont/shared/.conda/envs/grapetree_2.1/lib/python3.6/site-packages/grapetree/module/MSTrees.py", line 282, in get_shortcut
[cgMLST0_toy.txt](https://github.com/achtman-lab/GrapeTree/files/11105314/cgMLST0_toy.txt)

    link = link.T[np.lexsort(link)]
  File "<__array_function__ internals>", line 6, in lexsort
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johnsont/shared/.conda/envs/grapetree_2.1/bin/grapetree", line 10, in <module>
    sys.exit(main())
  File "/home/johnsont/shared/.conda/envs/grapetree_2.1/lib/python3.6/site-packages/grapetree/grapetree.py", line 62, in main
    print (backend(**add_args()))
  File "/home/johnsont/shared/.conda/envs/grapetree_2.1/lib/python3.6/site-packages/grapetree/module/MSTrees.py", line 730, in backend
    tre = eval('methods.' + params['method'])(names, profiles, embeded, **params)
  File "/home/johnsont/shared/.conda/envs/grapetree_2.1/lib/python3.6/site-packages/grapetree/module/MSTrees.py", line 447, in MSTree
    tree = eval('methods._'+matrix_type)(dist, weight, **params)
  File "/home/johnsont/shared/.conda/envs/grapetree_2.1/lib/python3.6/site-packages/grapetree/module/MSTrees.py", line 323, in _asymmetric
    shortcuts = get_shortcut(wdist, weight)
  File "/home/johnsont/shared/.conda/envs/grapetree_2.1/lib/python3.6/site-packages/grapetree/module/MSTrees.py", line 282, in get_shortcut
    link = link.T[np.lexsort(link)]
  File "<__array_function__ internals>", line 6, in lexsort
MemoryError
```
[cgMLST0_toy.txt](https://github.com/achtman-lab/GrapeTree/files/11105318/cgMLST0_toy.txt)

**Comment by happykhan** [comment]
Update: draft PR #118 replaces the quadratic shortcut-coordinate allocation with a column-wise selector. Randomised equivalence tests lock the legacy edge and tie behaviour, and a dense test proves linear shortcut storage. The underlying distance matrix remains quadratic and is documented as the next scaling boundary. The PR is configured to close this issue when merged.
