### ISSUE TITLE
grapetree and Python 3.6

### ISSUE THREAD

**Issue by crarlus** [achtman-lab/GrapeTree#80]
Hi,
I am trying to run grapetree with python 3.6. 
* I created a conda environment with python 3.6.7 and pip
* I installed grapetree via `pip install grapetree`
> Successfully installed DendroPy-4.4.0 Flask-1.0.2 Jinja2-2.10 MarkupSafe-1.1.1 Werkzeug-0.14.1 click-7.0 decorator-4.3.2 grapetree-1.5 itsdangerous-1.1.0 llvmlite-0.27.1 networkx-2.2 numba-0.42.1 numpy-1.16.2 psutil-5.5.1
* I get the following error message
```
$ grapetree -h
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/grapetree3/bin/grapetree", line 6, in <module>
    from grapetree.grapetree import main
  File "/home/user/anaconda3/envs/grapetree3/lib/python3.6/site-packages/grapetree/grapetree.py", line 29, in <module>
    from module import app
ModuleNotFoundError: No module named 'module'
```

The same works however when I install a conda environment with python 2.7

Do you have any hints? Thanks!

**Comment by zheminzhou** [comment]
It has now been fully tested and updated to work in python 3.6.

**Comment by martinbaste** [comment]
I'm still seeing this issue. I created a clean environment using conda for python3.6. I tried installing from pypi repository and also from this gh repository by using `pip install git+<url>`. Getting the same message  in both cases.

`ModuleNotFoundError: No module named 'module'`

**Comment by luolyaduo** [comment]
python /home/user/anaconda3/envs/grapetree3/lib/python3.6/site-packages/grapetree/grapetree.py -h 
will work. But I meet with another problem of numba.

**Comment by dutchscientist** [comment]
I have the same problem as https://github.com/achtman-lab/GrapeTree/issues/80#issuecomment-504987898. Separate Conda environments for python 3.6 does not make a difference. I can run it in a separate environment for 2.7 (lots of warnings though).

Ubuntu 16.04.

**Comment by mabouelk** [comment]
I have the same problem, is there any help ?

File "/Users/moh/anaconda2/bin/grapetree", line 5, in <module>
    from grapetree.grapetree import main
  File "/Users/moh/anaconda2/lib/python2.7/site-packages/grapetree/grapetree.py", line 33, in <module>
    from module import app
ImportError: No module named module
