### ISSUE TITLE
GrapeTree is still available???

### ISSUE THREAD

**Issue by mabouelk** [achtman-lab/GrapeTree#88]
Hi, 
I am having hard time installing this tool: 

Traceback (most recent call last):
  File "/Users/moh/miniconda3/bin/grapetree", line 5, in <module>
    from grapetree.grapetree import main
  File "/Users/moh/miniconda3/lib/python3.7/site-packages/grapetree/grapetree.py", line 33, in <module>
    from module import app
ModuleNotFoundError: No module named 'module'

I tried the github version, macOS, windows, source and everything!!!!

**Comment by zheminzhou** [comment]
A new version of 2.2 has just released. It works on python >= 3.5 in our test environment.
