### ISSUE TITLE
Estimate breaks with ninja and distance methods

### ISSUE THREAD

**Issue by peterjc** [achtman-lab/GrapeTree#99]
Tested on Linux,

```
$ pip freeze | grep grapetree
grapetree==2.2
```

There are 6 documented methods:

```
$ grapetree -h | grep "\--method" -A 6
usage: grapetree [-h] --profile FNAME [--method TREE] [--matrix MATRIX_TYPE]
                 [--recraft] [--missing HANDLER] [--wgMLST]
                 [--heuristic HEURISTIC] [--n_proc NUMBER_OF_PROCESSES]
                 [--check] [--block_penalty BLOCK_PENALTY]

For details, see "https://github.com/achtman-lab/GrapeTree/blob/master/README.md".
In brief, GrapeTree generates a NEWICK tree to the default output (screen) 
--
  --method TREE, -m TREE
                        "MSTreeV2" [DEFAULT]
                        "MSTree"
                        "NJ": FastME V2 NJ tree
                        "RapidNJ": RapidNJ for very large datasets
                        "ninja": Alternative NJ algorithm for very large datasets
                        "distance": allelic distance matrix in PHYLIP format.
```

The ``-c`` or ``--check`` option to only calculate the expected time/memory requirements works for just the first four methods:

```
$ for M in MSTreeV2 MSTree NJ RapidNJ ninja distance; do echo $M; grapetree -p Grapetree_Agona.profile -m $M -c; done
MSTreeV2
{"time": 33.77119490714262, "memory": 517090823.53, "affordable": true}
MSTree
{"time": 32.64200608256635, "memory": 429867607.233, "affordable": true}
NJ
{"time": 5, "memory": 52428800, "affordable": true}
RapidNJ
{"time": 32.64200608256635, "memory": 429867607.233, "affordable": true}
ninja
Traceback (most recent call last):
  File "/mnt/.../conda/bin/grapetree", line 8, in <module>
    sys.exit(main())
  File "/mnt/.../conda/lib/python3.7/site-packages/grapetree/grapetree.py", line 62, in main
    print (backend(**add_args()))
  File "/mnt/s.../conda/lib/python3.7/site-packages/grapetree/module/MSTrees.py", line 721, in backend
    time, memory = estimate_Consumption(platform.system(), params['method'], params['matrix_type'], int(params['n_proc']), profiles.shape[1], profiles.shape[0])
  File "/mnt/.../conda/lib/python3.7/site-packages/grapetree/module/MSTrees.py", line 786, in estimate_Consumption
    return max(time, 5), max(memory, 50*1024*1024)
UnboundLocalError: local variable 'time' referenced before assignment
distance
Traceback (most recent call last):
  File "/mnt/.../conda/bin/grapetree", line 8, in <module>
    sys.exit(main())
  File "/mnt/.../conda/lib/python3.7/site-packages/grapetree/grapetree.py", line 62, in main
    print (backend(**add_args()))
  File "/mnt/.../conda/lib/python3.7/site-packages/grapetree/module/MSTrees.py", line 721, in backend
    time, memory = estimate_Consumption(platform.system(), params['method'], params['matrix_type'], int(params['n_proc']), profiles.shape[1], profiles.shape[0])
  File "/mnt/.../conda/lib/python3.7/site-packages/grapetree/module/MSTrees.py", line 786, in estimate_Consumption
    return max(time, 5), max(memory, 50*1024*1024)
UnboundLocalError: local variable 'time' referenced before assignment
```

The estimate_Consumption if statement needs an else statement for methods without an estimate here:

https://github.com/achtman-lab/GrapeTree/blob/f92fe3e04247fef9b080abcb0fe14b4b3fd0b8ab/module/MSTrees.py#L781

**Comment by happykhan** [comment]
Update: draft PR #118 fixes environment estimation for distance calculations and hardens all HTTP boolean option parsing. Backend and route regressions cover the affected path. The PR is configured to close this issue when merged.
